language: objective-c
osx_image: xcode9

env:
  - ACTION=test  PLATFORM=macOS   DESTINATION='platform=OS X'
  - ACTION=build PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
  - ACTION=build PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'
  - ACTION=build PLATFORM=watchOS DESTINATION='platform=watchOS Simulator,name=Apple Watch - 42mm'

script:
  - set -o pipefail && xcodebuild -workspace ColorArtwork.xcworkspace -scheme "ColorArtwork-Package" -destination "$DESTINATION" $ACTION | xcpretty
